import { useState, useEffect, useCallback, useRef } from 'react'
import { pictureApi } from '../api/picture'

export type TaskStatus = 
  | 'PENDING'      // 排队中
  | 'RUNNING'      // 处理中
  | 'SUSPENDED'    // 挂起
  | 'SUCCEEDED'    // 执行成功
  | 'FAILED'       // 执行失败
  | 'UNKNOWN'      // 任务不存在或状态未知

export interface OutPaintingTaskResult {
  taskId: string
  taskStatus: TaskStatus
  submitTime?: string
  scheduledTime?: string
  endTime?: string
  outputImageUrl?: string
  code?: string
  message?: string
  // 任务指标信息
  taskMetrics?: {
    total?: number
    succeeded?: number
    failed?: number
  }
}

export interface OutPaintingParameters {
  /**
   * 逆时针旋转角度，默认值 0，取值范围 [0, 359]
   */
  angle?: number
  /**
   * 输出图像的宽高比，默认空字符串，不设置宽高比
   * 可选值：["", "1:1", "3:4", "4:3", "9:16", "16:9"]
   */
  outputRatio?: string
  /**
   * 图像居中，在水平方向上按比例扩展，默认值 1.0，范围 [1.0, 3.0]
   */
  xScale?: number
  /**
   * 图像居中，在垂直方向上按比例扩展，默认值 1.0，范围 [1.0, 3.0]
   */
  yScale?: number
  /**
   * 在图像上方添加像素，默认值 0
   */
  topOffset?: number
  /**
   * 在图像下方添加像素，默认值 0
   */
  bottomOffset?: number
  /**
   * 在图像左侧添加像素，默认值 0
   */
  leftOffset?: number
  /**
   * 在图像右侧添加像素，默认值 0
   */
  rightOffset?: number
  /**
   * 开启图像最佳质量模式，默认值 false
   * 若为 true，耗时会成倍增加
   */
  bestQuality?: boolean
  /**
   * 限制模型生成的图像文件大小，默认值 true
   * - 单边长度 <= 10000：输出图像文件大小限制为 5MB 以下
   * - 单边长度 > 10000：输出图像文件大小限制为 10MB 以下
   */
  limitImageSize?: boolean
  /**
   * 添加 "Generated by AI" 水印，默认值 true
   */
  addWatermark?: boolean
}

interface UseImageTaskPollingReturn {
  taskId: string | null
  taskResult: OutPaintingTaskResult | null
  isPolling: boolean
  isLoading: boolean
  error: string | null
  startPolling: (taskId: string) => void
  stopPolling: () => void
  reset: () => void
}

/**
 * AI 扩图任务轮询 Hook
 * @param pollInterval 轮询间隔（毫秒），默认 2500ms
 * @param timeout 超时时间（毫秒），默认 2 分钟
 */
export function useImageTaskPolling(pollInterval: number = 2500, timeout: number = 120000): UseImageTaskPollingReturn {
  const [taskId, setTaskId] = useState<string | null>(null)
  const [taskResult, setTaskResult] = useState<OutPaintingTaskResult | null>(null)
  const [isPolling, setIsPolling] = useState(false)
  const [isLoading, setIsLoading] = useState(false)
  const [error, setError] = useState<string | null>(null)
  
  const timerRef = useRef<NodeJS.Timeout | null>(null)
  const timeoutRef = useRef<NodeJS.Timeout | null>(null)
  const isComponentMounted = useRef(true)
  const startTimeRef = useRef<number>(0)
  const initDelayRef = useRef<NodeJS.Timeout | null>(null)
  
  // 使用 ref 跟踪是否应该继续轮询（避免闭包问题）
  const shouldContinuePollingRef = useRef(false)

  // 清理定时器
  const clearTimer = useCallback(() => {
    shouldContinuePollingRef.current = false
    
    if (timerRef.current) {
      clearInterval(timerRef.current)
      timerRef.current = null
    }
    if (timeoutRef.current) {
      clearTimeout(timeoutRef.current)
      timeoutRef.current = null
    }
    if (initDelayRef.current) {
      clearTimeout(initDelayRef.current)
      initDelayRef.current = null
    }
  }, [])

  // 停止轮询
  const stopPolling = useCallback(() => {
    console.log('[AI 扩图] 🛑 stopPolling 被调用')
    shouldContinuePollingRef.current = false
    setIsPolling(false)
    clearTimer()
  }, [clearTimer])

  // 重置状态
  const reset = useCallback(() => {
    stopPolling()
    setTaskId(null)
    setTaskResult(null)
    setError(null)
    setIsLoading(false)
    startTimeRef.current = 0
  }, [stopPolling])

  // 查询任务状态
  const checkTaskStatus = useCallback(async (currentTaskId: string) => {
    try {
      console.log('[AI 扩图]  开始查询任务状态，taskId:', currentTaskId)
      const res = await pictureApi.getOutPaintingTask(currentTaskId)
      
      // 详细日志记录
      console.log('[AI 扩图] ====== 轮询响应开始 ======')
      console.log('[AI 扩图] res (已解包):', res)
      console.log('[AI 扩图] res.output:', res?.output)
      
      if (!isComponentMounted.current) {
        console.log('[AI 扩图] ⚠️ 组件已卸载，忽略此次响应')
        return
      }
      
      // 注意：pictureApi.getOutPaintingTask 已经返回 res.data.data = { requestId, output }
      // 所以这里直接访问 res.output
      const output = res?.output || {}
      console.log('[AI 扩图]  output 对象详细信息:')
      console.log('[AI 扩图]   - taskId:', output.taskId)
      console.log('[AI 扩图]   - taskStatus:', output.taskStatus)
      console.log('[AI 扩图]   - outputImageUrl:', output.outputImageUrl)
      console.log('[AI 扩图]   - submitTime:', output.submitTime)
      console.log('[AI 扩图]   - scheduledTime:', output.scheduledTime)
      console.log('[AI 扩图]   - endTime:', output.endTime)
      console.log('[AI 扩图]   - code:', output.code)
      console.log('[AI 扩图]   - message:', output.message)
      console.log('[AI 扩图]   - taskMetrics:', output.taskMetrics)
      
      // 构建任务结果对象
      const mappedResult: OutPaintingTaskResult = {
        taskId: output.taskId || currentTaskId,
        taskStatus: output.taskStatus as TaskStatus,
        submitTime: output.submitTime,
        scheduledTime: output.scheduledTime,
        endTime: output.endTime,
        outputImageUrl: output.outputImageUrl,
        code: output.code,
        message: output.message,
        taskMetrics: output.taskMetrics
      }
      
      // 更新任务结果状态
      setTaskResult(mappedResult)
      
      // 检查任务状态并决定是否停止轮询
      const status = output.taskStatus
      console.log('[AI 扩图] 当前任务状态:', status, '| 是否继续轮询 ref:', shouldContinuePollingRef.current)
      
      if (status === 'SUCCEEDED') {
        // 任务成功 - 立即停止轮询
        console.log('[AI 扩图] ✅ 任务执行成功！outputImageUrl:', output.outputImageUrl)
        console.log('[AI 扩图] 🛑 检测到 SUCCEEDED，立即停止轮询')
        shouldContinuePollingRef.current = false  // 直接设置 ref
        stopPolling()
        setIsLoading(false)
        return  // 重要：直接返回，防止继续执行
      } else if (status === 'FAILED') {
        // 任务失败 - 停止轮询并显示错误
        const errorMsg = output.message || output.code || '未知错误'
        console.log('[AI 扩图] ❌ 任务执行失败:', errorMsg)
        setError('扩图失败：' + errorMsg)
        shouldContinuePollingRef.current = false
        stopPolling()
        setIsLoading(false)
        return
      } else if (status === 'UNKNOWN') {
        // 任务不存在或状态未知
        console.log('[AI 扩图] ️ 任务不存在或状态未知')
        setError('任务不存在或状态未知，请稍后重试')
        shouldContinuePollingRef.current = false
        stopPolling()
        setIsLoading(false)
        return
      } else {
        // 其他状态（PENDING/RUNNING/SUSPENDED）- 继续轮询
        const statusText = {
          PENDING: '排队中',
          RUNNING: '处理中',
          SUSPENDED: '挂起'
        }[status] || status
        
        console.log(`[AI 扩图] ⏳ 任务进行中 [${statusText}]，继续轮询...`)
      }
      
    } catch (err) {
      console.error('[AI 扩图] ❌ 查询任务状态失败:', err)
      if (isComponentMounted.current) {
        setError('查询任务状态失败：' + (err as Error).message)
        stopPolling()
        setIsLoading(false)
      }
    }
  }, [stopPolling])

  // 开始轮询
  const startPolling = useCallback((newTaskId: string) => {
    console.log('[AI 扩图]  开始轮询任务:', newTaskId, '间隔:', pollInterval, 'ms, 超时:', timeout, 'ms')
    
    // 清除之前的定时器
    clearTimer()
    
    // 设置轮询标志
    shouldContinuePollingRef.current = true
    console.log('[AI 扩图] 设置 shouldContinuePollingRef = true')
    
    setTaskId(newTaskId)
    setIsPolling(true)
    setIsLoading(true)
    setError(null)
    setTaskResult(null)
    startTimeRef.current = Date.now()
    
    // 设置超时定时器
    timeoutRef.current = setTimeout(() => {
      if (isComponentMounted.current && shouldContinuePollingRef.current) {
        const elapsed = Math.round((Date.now() - startTimeRef.current) / 1000)
        console.warn('[AI 扩图] ⏰ 任务超时，已耗时:', elapsed, '秒')
        setError(`任务超时（${elapsed}秒），请稍后重试或联系客服`)
        stopPolling()
        setIsLoading(false)
      }
    }, timeout)
    
    // 立即查询一次
    checkTaskStatus(newTaskId)
    
    // 设置定时器（等待 500ms 后再开始，避免与首次查询冲突）
    initDelayRef.current = setTimeout(() => {
      if (isComponentMounted.current && shouldContinuePollingRef.current) {
        console.log('[AI 扩图]  设置轮询定时器')
        timerRef.current = setInterval(() => {
          // 每次执行前检查是否应该继续
          if (!shouldContinuePollingRef.current) {
            console.log('[AI 扩图] 🛑 定时器检测到 shouldContinuePollingRef = false，停止轮询')
            clearInterval(timerRef.current!)
            timerRef.current = null
            return
          }
          console.log('[AI 扩图]  执行轮询检查...')
          checkTaskStatus(newTaskId)
        }, pollInterval)
      }
    }, 500)
    
  }, [clearTimer, checkTaskStatus, pollInterval, timeout, stopPolling])

  // 组件卸载时清理
  useEffect(() => {
    isComponentMounted.current = true
    
    return () => {
      isComponentMounted.current = false
      clearTimer()
    }
  }, [clearTimer])

  return {
    taskId,
    taskResult,
    isPolling,
    isLoading,
    error,
    startPolling,
    stopPolling,
    reset
  }
}
